### ISSUE TITLE
does not start- TSC error

### ISSUE THREAD

**Issue by srl295** [katsew/logotron#14]
> assets/js/code-runner/index.ts(52,23): error TS2695: Left side of comma operator is unused and has no side effects.

worked around with: 

```diff
-      debug(`delta: ${now, this.lastTimeMilli}`);
+      debug(`delta: ${now}, ${this.lastTimeMilli}`);
```

**Comment by katsew** [comment]
@srl295 

Thanks for reporting the issue.  
I fixed this on v0.4.0 and released.  

If you still have the same problem, please reopen this issue, thanks.
